### ISSUE TITLE
RangeError when trying to transfer to S3

### ISSUE THREAD

**Issue by guillaumecostanza** [parse-server-modules/parse-files-utils#17] opened 2016-09-09 21:51 UTC
Hi,

I'm stuck via this error : 

? About to start the file transfer. Does the above look correct? Yes
Initializing transfer configuration...
Initializing s3 adapter
Fetching schema...
Fetching all objects with files...
Processing 5944 files
Saving files with s3
{ [RangeError: Maximum call stack size exceeded] undefined: true }

Could you help ?

config :

var FileAdapter = require('parse-server-fs-adapter');
var S3Adapter = require('parse-server-s3-adapter');

module.exports = {
    applicationId: "xxx",
    masterKey: "xxx",
    mongoURL: "xxx",
    serverURL: "http://xxx/parse",
    filesToTransfer: 'parseOnly',
    renameInDatabase: false,
    renameFiles: false,
    transferTo: 's3',
    aws_accessKeyId: "xxx",
    aws_secretAccessKey: "xxx",
    aws_bucket: "xxx",
    aws_bucketPrefix: "xxx"
};

npm logs :

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start',
1 verbose cli   'config.js' ]
2 info using npm@3.8.6
3 info using node@v5.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle parse-files-utils@0.0.1~prestart: parse-files-utils@0.0.1
6 silly lifecycle parse-files-utils@0.0.1~prestart: no script for prestart, continuing
7 info lifecycle parse-files-utils@0.0.1~start: parse-files-utils@0.0.1
8 verbose lifecycle parse-files-utils@0.0.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle parse-files-utils@0.0.1~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/guillaumecostanzapersonal/Developement/parse-files-utils/node_modules/.bin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/MacGPG2/bin
10 verbose lifecycle parse-files-utils@0.0.1~start: CWD: /Users/guillaumecostanzapersonal/Developement/parse-files-utils
11 silly lifecycle parse-files-utils@0.0.1~start: Args: [ '-c', 'node index.js "config.js"' ]
12 silly lifecycle parse-files-utils@0.0.1~start: Returned: code: 1  signal: null
13 info lifecycle parse-files-utils@0.0.1~start: Failed to exec start script
14 verbose stack Error: parse-files-utils@0.0.1 start: `node index.js "config.js"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:818:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid parse-files-utils@0.0.1
16 verbose cwd /Users/guillaumecostanzapersonal/Developement/parse-files-utils
17 error Darwin 15.6.0
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "config.js"
19 error node v5.1.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error parse-files-utils@0.0.1 start: `node index.js "config.js"`
22 error Exit status 1
23 error Failed at the parse-files-utils@0.0.1 start script 'node index.js "config.js"'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the parse-files-utils package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     node index.js "config.js"
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs parse-files-utils
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls parse-files-utils
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by guillaumecostanza** [comment] 2016-09-09 22:00
I've been able to complete the transfer by using filesToTransfer: 'all'.

**Comment by acinader** [comment] 2016-09-09 22:18
I think that in your conf, you want:

serverURL: "https://api.parse.com/1",

'cause what you're doing is copying the files that are on parse to your own s3 bucket.

And I'm guessing that what you want is:

filesToTransfer: 'parseOnly',

'cause you just want to copy the files that parse thinks are on parse to your bucket.

**Comment by guillaumecostanza** [comment] 2016-09-09 22:33
As long as the file key is configured, isn't it the same if I user host parse serverURL or my own parse server (with same DB) ?

Unfortunately, even with hosted app, I keep getting the same error

**Comment by acinader** [comment] 2016-09-09 23:25
yeah, you're right the server url shouldn't matter....just comparing with what i did and i noticed that.

https://github.com/parse-server-modules/parse-files-utils/blob/master/lib/transfer.js#L131

you could try setting ```asyncLimit``` to 1 in your config.js file and see if it cures the error?

out of curiosity, what kind of machine are you running on?

**Comment by guillaumecostanza** [comment] 2016-09-09 23:42
Same result with the async limit set to 1, i'm running on mac (10.11.6)

**Comment by acinader** [comment] 2016-09-09 23:52
hm.  me too.

```
node --version
v6.3.1
```

**Comment by spenceps** [comment] 2016-11-12 15:39
I'm getting something similar as well.  I had run the migration before and a lot of the files are already transferred. I think it has to do with checking if the current file is a parse type file in a synchronous function. I think that if the `_shouldTransferFile` in transfer.js returns false too many times in a row it won't get to the next tick and the call stack won't be cleared ever.  Just checking to see if this makes sense to anybody before I try changing _shouldTransferFile to be asynchronous.

```
Processing 327172 files
Saving files with s3
RangeError: Maximum call stack size exceeded
    at new TickObject (internal/process/next_tick.js:136:26)
    at process.nextTick (internal/process/next_tick.js:154:24)
    at onwrite (_stream_writable.js:376:15)
    at WritableState.onwrite (_stream_writable.js:89:5)
    at WriteStream.Socket._writeGeneric (net.js:719:5)
    at WriteStream.Socket._write (net.js:729:8)
    at doWrite (_stream_writable.js:333:12)
    at writeOrBuffer (_stream_writable.js:319:5)
    at WriteStream.Writable.write (_stream_writable.js:246:11)
    at WriteStream.Socket.write (net.js:656:40)
```

**Comment by benjaminmcdonald** [comment] 2016-12-01 07:32
@spenceps

I also had this error after running the script for a second time after a "renameInDatabase: true". I checked the database and the files were not renamed. When I tried running it a second time I got

RangeError: Maximum call stack size exceeded....

**Comment by acinader** [comment] 2016-12-01 16:46
the problem is that the tool is collecting all of the names before processing them, so there's a limit on how many it can handle.  to fix, it'd have to do the transfer in batches....

**Comment by stromdotcom** [comment] 2016-12-11 17:36
Have the exact same issue as @benjaminmcdonald .  First run processed about 1/3 of files (30k or so).  Second and all subsequent runs error out with RangeError.

**Comment by sirioz** [comment] 2016-12-28 22:38
I solved it replacing `callback()` with `process.nextTick(callback)` in line 139 of transfer.js.

**Comment by stromdotcom** [comment] 2016-12-28 23:29
Thanks @sirioz it seems to be working again with that change!

**Comment by acinader** [comment] 2017-01-09 23:20
@sirioz can you make a pull request with that change please?

**Closed** 2017-02-08 23:25 UTC
